# tests/test_python_test_writer.py

from __future__ import annotations

from pathlib import Path

import pytest

from llmtestgen.services.test_generation.test_spec_generator import (
    TestCase,
    TestSpecification,
)
from llmtestgen.services.test_generation.python_test_writer import (
    render_test_case_pytest,
    render_test_spec_file,
    write_test_spec_file,
)


def test_render_test_case_pytest_with_requirement():
    """A TestCase with a requirement should render a pytest function including docstring and TODO placeholder."""
    tc = TestCase(
        id="login_valid_credentials",
        requirement="The system must allow login with valid credentials.",
        description="Login with valid username and password",
        preconditions=["User exists in database"],
        steps=[
            "Open the login page",
            "Enter a valid username and password",
            "Click the login button",
        ],
        expected_result="The user is logged in and redirected to the dashboard.",
        target_code_elements=["auth/login.py"],
    )

    code = render_test_case_pytest(tc, index=1)

    # Function name must start with test_001_
    assert code.strip().startswith("def test_001_")

    # Requirement should appear in the docstring
    assert "Requirement: The system must allow login with valid credentials." in code

    # Preconditions must appear in commented form
    assert "# Preconditions" in code
    assert "# - User exists in database" in code

    # Steps must appear
    assert "# Steps" in code
    assert "# 1. Open the login page" in code
    assert "# 2. Enter a valid username and password" in code

    # Expected result must appear
    assert "# Expected result" in code
    assert "The user is logged in and redirected to the dashboard." in code

    # Must contain the assert False placeholder
    assert 'assert False, "Not implemented yet"' in code


def test_render_test_case_pytest_without_requirement_uses_description():
    """If no requirement is provided, the description should appear in the docstring."""
    tc = TestCase(
        id=None,
        requirement=None,
        description="Add two positive integers",
        preconditions=[],
        steps=["Call add(2, 3)"],
        expected_result="The result should be 5.",
        target_code_elements=[],
    )

    code = render_test_case_pytest(tc, index=2)

    # Description must appear in the docstring
    assert "Description: Add two positive integers" in code

    # Function name must start with test_002_
    assert "def test_002_" in code


def test_render_test_spec_file_generates_multiple_functions():
    """A full TestSpecification containing multiple cases should render multiple pytest functions."""
    spec = TestSpecification(
        spec_source_path="specs/demo_spec.yaml",
        llm_model="test-model",
        test_cases=[
            TestCase(
                id="case_1",
                requirement="Req 1",
                description="First test",
                preconditions=[],
                steps=["Step A"],
                expected_result="Result A",
                target_code_elements=[],
            ),
            TestCase(
                id="case_2",
                requirement="Req 2",
                description="Second test",
                preconditions=[],
                steps=["Step B"],
                expected_result="Result B",
                target_code_elements=[],
            ),
        ],
    )

    code = render_test_spec_file(spec)

    # Module-level docstring must appear
    assert "Auto-generated test module from LLMTestGen." in code
    assert "Source spec: specs/demo_spec.yaml" in code
    assert "Generated by model: test-model" in code

    # Should generate exactly two test functions
    assert code.count("def test_001_") == 1
    assert code.count("def test_002_") == 1


def test_render_test_spec_file_no_test_cases():
    """If no test cases are present, the file should contain an explicit message."""
    spec = TestSpecification(
        spec_source_path="specs/empty.yaml",
        llm_model=None,
        test_cases=[],
    )

    code = render_test_spec_file(spec)

    assert "# No test cases were generated." in code


def test_write_test_spec_file_writes_to_disk(tmp_path: Path):
    """write_test_spec_file should create a .py file with non-empty content."""
    spec = TestSpecification(
        spec_source_path="specs/demo_spec.yaml",
        llm_model=None,
        test_cases=[
            TestCase(
                id="simple_case",
                requirement=None,
                description="Simple test",
                preconditions=[],
                steps=[],
                expected_result="It should do something.",
                target_code_elements=[],
            ),
        ],
    )

    output_path = tmp_path / "generated_tests" / "test_generated.py"

    written_path = write_test_spec_file(spec, output_path=output_path)

    # Path returned must match the input
    assert written_path == output_path

    # File should exist
    assert output_path.is_file()

    # Content must be non-empty and contain at least one test function
    content = output_path.read_text(encoding="utf-8")
    assert "def test_001_" in content
    assert 'assert False, "Not implemented yet"' in content
